server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tododb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  flyway:
    enabled: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:my-super-secret-jwt-key-for-todo-app-change-in-production-min-256-bits}
  expiration-minutes: ${JWT_EXP_MIN:60}
  refresh-expiration-minutes: ${REFRESH_EXP_MIN:10080}

# Rate Limiting Configuration
rate-limit:
  auth:
    capacity: ${RATE_LIMIT_AUTH_CAPACITY:10}
    refill-tokens: ${RATE_LIMIT_AUTH_REFILL:10}
    refill-duration-minutes: ${RATE_LIMIT_AUTH_DURATION:10}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.todoapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
